backend:
  name: github
  repo: shivam201720/https-aajseshivampriyhindike.netlify.app
  branch: main

media_folder: "IMG"
public_folder: "/IMG"

collections:
  - name: "udgaar"
    label: "उद्गार"
    folder: "udgaar"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "शीर्षक", name: "title", widget: "string" }
      - { label: "दिनांक", name: "date", widget: "datetime" }
      - { label: "कविता / लेख", name: "body", widget: "markdown" }

  - name: "sampark"
    label: "संपर्क"
    folder: "sampark"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "नाम", name: "name", widget: "string" }
      - { label: "ईमेल", name: "email", widget: "string" }
      - { label: "संदेश", name: "message", widget: "text" }
