backend:
  name: github
  repo: shivam201720/https-aajseshivampriyhindike.netlify.app
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "udgaar"
    label: "उद्गार"
    folder: "udgaar"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "शीर्षक", name: "title", widget: "string" }
      - { label: "कविता", name: "body", widget: "markdown" }
